export enum Intents {
  StartCall = 'StartCall',
  StartChat = 'StartChat',
  StartEmail = 'StartEmail',
  ViewAnalysis = 'ViewAnalysis',
  ViewChart = 'ViewChart',
  ViewContact = 'ViewContact',
  ViewHoldings = 'ViewHoldings',
  ViewInstrument = 'ViewInstrument',
  ViewInteractions = 'ViewInteractions',
  ViewNews = 'ViewNews',
  ViewOrders = 'ViewOrders',
  ViewProfile = 'ViewProfile',
  ViewQuote = 'ViewQuote',
  ViewResearch = 'ViewResearch',
  CreateInteraction = 'CreateInteraction',
}
