name: Node.js CI Tests and Coverage

# Controls when the workflow will run on any branch
on:
  push:
    branches:
      - main
  pull_request:

# Allows Coverage to be written back as a PR comment
permissions: 
  pull-requests: write

# Define the jobs for this workflow
jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    strategy:
      matrix:
        node-version: [22]

    steps:
    - name: Checkout repository
      uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

    - name: Set up Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Run tests
      run: npm run test

    - name: Codecov
      uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
