name: Static code analysis

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  schedule:
    # Run every day at 5am and 5pm
    - cron: '0 5,17 * * *'

permissions:
  contents: read

jobs:
  semgrep:
    name: run-semgrep
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
    - name: Harden runner
      uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
      with:
        egress-policy: audit

    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Run Semgrep
      run: semgrep scan --error --config auto
      env:
        SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
